# Generated by Django 4.0 on 2022-03-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designation',
            old_name='designationd_esignation',
            new_name='designation_name',
        ),
    ]
