# Generated by Django 4.0 on 2022-03-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0002_rename_designationd_esignation_designation_designation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create_team',
            old_name='create_team_team_count',
            new_name='create_team_count',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_attendance_status',
        ),
        migrations.RemoveField(
            model_name='create_team',
            name='create_team_team_status',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_leave_status',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_topic_status',
        ),
        migrations.RemoveField(
            model_name='trainer_task',
            name='trainer_task_task_status',
        ),
        migrations.AlterField(
            model_name='create_team',
            name='create_team_status',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
